### ISSUE TITLE
No module named 'unitConverter'

### ISSUE THREAD

**Issue by blooalien** [soachishti/pyScanLib#3]
When I try to use this module on Python 3.6 on Kubuntu Linux 17.04, the import fails with the error:

```python
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-2f06ffb89662> in <module>()
----> 1 from pyScanLib import pyScanLib
      2 
      3 #======================================================================
      4 #       Name:       saneLib
      5 #   Location:   https://github.com/soachishti/pyScanLib

~/.local/virtualenvs/py3.6/lib/python3.6/site-packages/pyScanLib/__init__.py in <module>()
      1 import sys
----> 2 import unitConverter  # Contains unit converting functions ie millimeter to \
                              # inch (mmToInch) etc
      3 
      4 """
      5  * pyScanLib

ModuleNotFoundError: No module named 'unitConverter'
```

Where can I find this module `unitConverter` to import it, or install it?

**Comment by blooalien** [comment]
Sorry. Ignore this issue or delete it, please. I installed the code from GitHub instead of the one from `pip/PyPi`, and it works now.

**Comment by isaaccruzitc** [comment]
Hello, I'm having the same issue, how did you manage to solve it?
Thanks

**Comment by soachishti** [comment]
@isaaccruzitc  This seem like it is failing to resolve unitConverter when using from PyPi. You can download code from GitHub and use it directly in your project.

**Comment by isaaccruzitc** [comment]
I downloaded the code and it works correctly. 
Thanks for your help.
